class ExamData {
  final String title;
  final String country;
  final List<String> items;
  final bool isTestSections; // true for SAT/PSAT/ACT

  ExamData({
    required this.title,
    required this.country,
    required this.items,
    this.isTestSections = false,
  });
}

const Map<String, Map<String, List<String>>> examSubjectTopics = {
  // UK Exams
  'IGCSE': {
    'English Language': [
      'Reading Comprehension',
      'Vocabulary',
      'Grammar',
      'Essay Writing',
      'Summary Writing',
    ],
    'English Literature': ['will be adding soon'],
    'Mathematics': [
      'Numbers & Fractions',
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Geometry',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
    'Additional Mathematics': [
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
    'Biology': [
      'Cell Structure',
      'Enzymes',
      'Respiration',
      'Transport Systems',
      'Genetics',
      'Ecology',
    ],
    'Chemistry': [
      'Atomic Structure',
      'Bonding',
      'Periodic Table',
      'Stoichiometry',
      'Acids & Bases',
      'Reaction Rates',
      'Organic Basics',
    ],
    'Physics': [
      'Motion',
      'Forces',
      'Energy',
      'Electricity',
      'Waves',
      'Thermal Physics',
    ],
    'Combined Science': ['will be adding soon'],
    'Computer Science/ICT': ['will be adding soon'],
    'Business': [
      'Business Objectives',
      'Marketing',
      'Operations',
      'Finance',
      'Human Resources',
    ],
    'Economics': [
      'Demand & Supply',
      'Elasticity',
      'Inflation',
      'Market Structures',
      'Trade',
    ],
    'Accounting': [
      'Double Entry',
      'Financial Statements',
      'Cash Flow',
      'Depreciation',
    ],
    'Geography': ['will be adding soon'],
    'History': ['will be adding soon'],
    'Art & Design': ['will be adding soon'],
    'Foreign Language': ['will be adding soon'],
  },
  'GCSE': {
    'English Language': [
      'Reading Comprehension',
      'Vocabulary',
      'Grammar',
      'Essay Writing',
      'Summary Writing',
    ],
    'English Literature': ['will be adding soon'],
    'Mathematics': [
      'Numbers & Fractions',
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Geometry',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
    'Combined Science': ['will be adding soon'],
    'Biology': [
      'Cell Structure',
      'Enzymes',
      'Respiration',
      'Transport Systems',
      'Genetics',
      'Ecology',
    ],
    'Chemistry': [
      'Atomic Structure',
      'Bonding',
      'Periodic Table',
      'Stoichiometry',
      'Acids & Bases',
      'Reaction Rates',
      'Organic Basics',
    ],
    'Physics': [
      'Motion',
      'Forces',
      'Energy',
      'Electricity',
      'Waves',
      'Thermal Physics',
    ],
    'Computer Science': ['will be adding soon'],
    'Business': [
      'Business Objectives',
      'Marketing',
      'Operations',
      'Finance',
      'Human Resources',
    ],
    'Economics': [
      'Demand & Supply',
      'Elasticity',
      'Inflation',
      'Market Structures',
      'Trade',
    ],
    'Geography': ['will be adding soon'],
    'History': ['will be adding soon'],
    'Religious Studies': ['will be adding soon'],
    'Art & Design': ['will be adding soon'],
    'Design & Technology': ['will be adding soon'],
    'PE': ['will be adding soon'],
  },
  'A-LEVEL': {
    'Mathematics': [
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
    'Further Mathematics': [
      'Algebra',
      'Functions & Graphs',
      'Trigonometry',
      'Statistics',
    ],
    'Biology': [
      'Cell Structure',
      'Enzymes',
      'Respiration',
      'Transport Systems',
      'Genetics',
      'Ecology',
    ],
    'Chemistry': [
      'Atomic Structure',
      'Bonding',
      'Periodic Table',
      'Stoichiometry',
      'Acids & Bases',
      'Reaction Rates',
      'Organic Basics',
    ],
    'Physics': [
      'Motion',
      'Forces',
      'Energy',
      'Electricity',
      'Waves',
      'Thermal Physics',
    ],
    'Computer Science': ['will be adding soon'],
    'Economics': [
      'Demand & Supply',
      'Elasticity',
      'Inflation',
      'Market Structures',
      'Trade',
    ],
    'Business': [
      'Business Objectives',
      'Marketing',
      'Operations',
      'Finance',
      'Human Resources',
    ],
    'Accounting': [
      'Double Entry',
      'Financial Statements',
      'Cash Flow',
      'Depreciation',
    ],
    'Psychology': ['will be adding soon'],
    'Law': ['will be adding soon'],
    'History': ['will be adding soon'],
    'Geography': ['will be adding soon'],
  },
  'EdEXCEL': {
    'IGCSE Subjects': ['will be adding soon'],
    'A-Level Subjects': ['will be adding soon'],
    'International GCSE': ['will be adding soon'],
  },

  // US Exams
  'SAT': {
    'Reading & Writing': [
      'Reading Comprehension',
      'Vocabulary',
      'Grammar',
      'Essay Writing',
    ],
    'Math': [
      'Numbers & Fractions',
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Geometry',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
  },
  'PSAT': {
    'Reading & Writing': [
      'Reading Comprehension',
      'Vocabulary',
      'Grammar',
      'Essay Writing',
    ],
    'Math': [
      'Numbers & Fractions',
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Geometry',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
  },
  'ACT': {
    'English': [
      'Reading Comprehension',
      'Vocabulary',
      'Grammar',
      'Essay Writing',
    ],
    'Math': [
      'Numbers & Fractions',
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Geometry',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
    'Reading': ['Reading Comprehension', 'Vocabulary'],
    'Science': ['will be adding soon'],
    'Writing (optional)': ['Essay Writing'],
  },
  'AP': {
    'AP Calculus': [
      'Functions & Graphs',
      'Trigonometry',
    ],
    'AP Statistics': [
      'Statistics',
      'Probability',
    ],
    'AP Biology': [
      'Cell Structure',
      'Enzymes',
      'Respiration',
      'Transport Systems',
      'Genetics',
      'Ecology',
    ],
    'AP Chemistry': [
      'Atomic Structure',
      'Bonding',
      'Periodic Table',
      'Stoichiometry',
      'Acids & Bases',
      'Reaction Rates',
      'Organic Basics',
    ],
    'AP Physics': [
      'Motion',
      'Forces',
      'Energy',
      'Electricity',
      'Waves',
      'Thermal Physics',
    ],
    'AP Computer Science': ['will be adding soon'],
    'AP Economics': [
      'Demand & Supply',
      'Elasticity',
      'Inflation',
      'Market Structures',
      'Trade',
    ],
    'AP Psychology': ['will be adding soon'],
    'AP World History': ['will be adding soon'],
    'AP Government': ['will be adding soon'],
    'AP English': [
      'Reading Comprehension',
      'Vocabulary',
      'Grammar',
      'Essay Writing',
    ],
  },

  // Australia Exams
  'ATAR': {
    'English': [
      'Reading Comprehension',
      'Vocabulary',
      'Grammar',
      'Essay Writing',
      'Summary Writing',
    ],
    'Mathematics (General)': [
      'Numbers & Fractions',
      'Algebra',
      'Equations & Inequalities',
      'Geometry',
      'Statistics',
      'Probability',
    ],
    'Mathematics (Methods)': [
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
    'Mathematics (Specialist)': [
      'Algebra',
      'Functions & Graphs',
      'Trigonometry',
    ],
    'Biology': [
      'Cell Structure',
      'Enzymes',
      'Respiration',
      'Transport Systems',
      'Genetics',
      'Ecology',
    ],
    'Chemistry': [
      'Atomic Structure',
      'Bonding',
      'Periodic Table',
      'Stoichiometry',
      'Acids & Bases',
      'Reaction Rates',
      'Organic Basics',
    ],
    'Physics': [
      'Motion',
      'Forces',
      'Energy',
      'Electricity',
      'Waves',
      'Thermal Physics',
    ],
    'Economics': [
      'Demand & Supply',
      'Elasticity',
      'Inflation',
      'Market Structures',
      'Trade',
    ],
    'Business': [
      'Business Objectives',
      'Marketing',
      'Operations',
      'Finance',
      'Human Resources',
    ],
    'Accounting': [
      'Double Entry',
      'Financial Statements',
      'Cash Flow',
      'Depreciation',
    ],
    'Legal Studies': ['will be adding soon'],
    'Psychology': ['will be adding soon'],
    'Computer Science/IT': ['will be adding soon'],
  },
  'HSC': {
    'English (Standard/Advanced)': [
      'Reading Comprehension',
      'Vocabulary',
      'Grammar',
      'Essay Writing',
      'Summary Writing',
    ],
    'Mathematics (Standard/Advanced/Extension)': [
      'Numbers & Fractions',
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Geometry',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
    'Biology': [
      'Cell Structure',
      'Enzymes',
      'Respiration',
      'Transport Systems',
      'Genetics',
      'Ecology',
    ],
    'Chemistry': [
      'Atomic Structure',
      'Bonding',
      'Periodic Table',
      'Stoichiometry',
      'Acids & Bases',
      'Reaction Rates',
      'Organic Basics',
    ],
    'Physics': [
      'Motion',
      'Forces',
      'Energy',
      'Electricity',
      'Waves',
      'Thermal Physics',
    ],
    'Economics': [
      'Demand & Supply',
      'Elasticity',
      'Inflation',
      'Market Structures',
      'Trade',
    ],
    'Business Studies': [
      'Business Objectives',
      'Marketing',
      'Operations',
      'Finance',
      'Human Resources',
    ],
    'Legal Studies': ['will be adding soon'],
    'Psychology': ['will be adding soon'],
    'Software Design': ['will be adding soon'],
  },
  'VCE': {
    'English': [
      'Reading Comprehension',
      'Vocabulary',
      'Grammar',
      'Essay Writing',
      'Summary Writing',
    ],
    'Mathematics (General/Methods/Specialist)': [
      'Numbers & Fractions',
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Geometry',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
    'Biology': [
      'Cell Structure',
      'Enzymes',
      'Respiration',
      'Transport Systems',
      'Genetics',
      'Ecology',
    ],
    'Chemistry': [
      'Atomic Structure',
      'Bonding',
      'Periodic Table',
      'Stoichiometry',
      'Acids & Bases',
      'Reaction Rates',
      'Organic Basics',
    ],
    'Physics': [
      'Motion',
      'Forces',
      'Energy',
      'Electricity',
      'Waves',
      'Thermal Physics',
    ],
    'Economics': [
      'Demand & Supply',
      'Elasticity',
      'Inflation',
      'Market Structures',
      'Trade',
    ],
    'Business Management': [
      'Business Objectives',
      'Marketing',
      'Operations',
      'Finance',
      'Human Resources',
    ],
    'Accounting': [
      'Double Entry',
      'Financial Statements',
      'Cash Flow',
      'Depreciation',
    ],
    'Legal Studies': ['will be adding soon'],
    'Psychology': ['will be adding soon'],
    'Computing': ['will be adding soon'],
  },
  'QCE': {
    'English': [
      'Reading Comprehension',
      'Vocabulary',
      'Grammar',
      'Essay Writing',
      'Summary Writing',
    ],
    'Mathematics (General/Methods/Specialist)': [
      'Numbers & Fractions',
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Geometry',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
    'Biology': [
      'Cell Structure',
      'Enzymes',
      'Respiration',
      'Transport Systems',
      'Genetics',
      'Ecology',
    ],
    'Chemistry': [
      'Atomic Structure',
      'Bonding',
      'Periodic Table',
      'Stoichiometry',
      'Acids & Bases',
      'Reaction Rates',
      'Organic Basics',
    ],
    'Physics': [
      'Motion',
      'Forces',
      'Energy',
      'Electricity',
      'Waves',
      'Thermal Physics',
    ],
    'Economics': [
      'Demand & Supply',
      'Elasticity',
      'Inflation',
      'Market Structures',
      'Trade',
    ],
    'Business': [
      'Business Objectives',
      'Marketing',
      'Operations',
      'Finance',
      'Human Resources',
    ],
    'Accounting': [
      'Double Entry',
      'Financial Statements',
      'Cash Flow',
      'Depreciation',
    ],
    'Legal Studies': ['will be adding soon'],
    'Psychology': ['will be adding soon'],
    'Digital Solutions': ['will be adding soon'],
  },

  // Malaysia Exams
  'SPM': {
    'Bahasa Melayu': ['will be adding soon'],
    'English': [
      'Reading Comprehension',
      'Vocabulary',
      'Grammar',
      'Essay Writing',
      'Summary Writing',
    ],
    'Mathematics': [
      'Numbers & Fractions',
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Geometry',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
    'Additional Mathematics': [
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
    'Sejarah': ['will be adding soon'],
    'Biology': [
      'Cell Structure',
      'Enzymes',
      'Respiration',
      'Transport Systems',
      'Genetics',
      'Ecology',
    ],
    'Chemistry': [
      'Atomic Structure',
      'Bonding',
      'Periodic Table',
      'Stoichiometry',
      'Acids & Bases',
      'Reaction Rates',
      'Organic Basics',
    ],
    'Physics': [
      'Motion',
      'Forces',
      'Energy',
      'Electricity',
      'Waves',
      'Thermal Physics',
    ],
    'Accounting': [
      'Double Entry',
      'Financial Statements',
      'Cash Flow',
      'Depreciation',
    ],
    'Business': [
      'Business Objectives',
      'Marketing',
      'Operations',
      'Finance',
      'Human Resources',
    ],
    'Economics': [
      'Demand & Supply',
      'Elasticity',
      'Inflation',
      'Market Structures',
      'Trade',
    ],
    'Computer Science': ['will be adding soon'],
  },
  'STPM': {
    'General Studies': ['will be adding soon'],
    'Mathematics': [
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
    'Further Mathematics': [
      'Algebra',
      'Functions & Graphs',
      'Trigonometry',
    ],
    'Biology': [
      'Cell Structure',
      'Enzymes',
      'Respiration',
      'Transport Systems',
      'Genetics',
      'Ecology',
    ],
    'Chemistry': [
      'Atomic Structure',
      'Bonding',
      'Periodic Table',
      'Stoichiometry',
      'Acids & Bases',
      'Reaction Rates',
      'Organic Basics',
    ],
    'Physics': [
      'Motion',
      'Forces',
      'Energy',
      'Electricity',
      'Waves',
      'Thermal Physics',
    ],
    'Economics': [
      'Demand & Supply',
      'Elasticity',
      'Inflation',
      'Market Structures',
      'Trade',
    ],
    'Business Studies': [
      'Business Objectives',
      'Marketing',
      'Operations',
      'Finance',
      'Human Resources',
    ],
    'Accounting': [
      'Double Entry',
      'Financial Statements',
      'Cash Flow',
      'Depreciation',
    ],
  },
  'Matrikulasi': {
    'Mathematics': [
      'Algebra',
      'Equations & Inequalities',
      'Functions & Graphs',
      'Trigonometry',
      'Statistics',
      'Probability',
    ],
    'Chemistry': [
      'Atomic Structure',
      'Bonding',
      'Periodic Table',
      'Stoichiometry',
      'Acids & Bases',
      'Reaction Rates',
      'Organic Basics',
    ],
    'Physics': [
      'Motion',
      'Forces',
      'Energy',
      'Electricity',
      'Waves',
      'Thermal Physics',
    ],
    'Biology': [
      'Cell Structure',
      'Enzymes',
      'Respiration',
      'Transport Systems',
      'Genetics',
      'Ecology',
    ],
    'Accounting': [
      'Double Entry',
      'Financial Statements',
      'Cash Flow',
      'Depreciation',
    ],
    'Economics': [
      'Demand & Supply',
      'Elasticity',
      'Inflation',
      'Market Structures',
      'Trade',
    ],
    'Business': [
      'Business Objectives',
      'Marketing',
      'Operations',
      'Finance',
      'Human Resources',
    ],
  },
  'UPSR': {
    'Bahasa Melayu': ['will be adding soon'],
    'English': [
      'Reading Comprehension',
      'Vocabulary',
      'Grammar',
    ],
    'Mathematics': [
      'Numbers & Fractions',
      'Algebra',
      'Geometry',
    ],
    'Science': ['will be adding soon'],
  },
};

class ExamDatabase {
  static final Map<String, ExamData> _examMap = {
    // UK Exams
    'IGCSE': ExamData(
      title: 'IGCSE',
      country: 'UK',
      items: [
        'Mathematics',
        'Additional Mathematics',
        'English Language',
        'English Literature',
        'Biology',
        'Chemistry',
        'Physics',
        'Combined Science',
        'Computer Science/ICT',
        'Business',
        'Economics',
        'Accounting',
        'Geography',
        'History',
        'Art & Design',
        'Foreign Language',
      ],
    ),
    'GCSE': ExamData(
      title: 'GCSE',
      country: 'UK',
      items: [
        'Mathematics',
        'Combined Science',
        'Biology',
        'Chemistry',
        'Physics',
        'Computer Science',
        'English Language',
        'English Literature',
        'Business',
        'Economics',
        'Geography',
        'History',
        'Religious Studies',
        'Art & Design',
        'Design & Technology',
        'PE',
      ],
    ),
    'A-LEVEL': ExamData(
      title: 'A-Level',
      country: 'UK',
      items: [
        'Mathematics',
        'Further Mathematics',
        'Biology',
        'Chemistry',
        'Physics',
        'Computer Science',
        'Economics',
        'Business',
        'Accounting',
        'Psychology',
        'Law',
        'History',
        'Geography',
      ],
    ),
    'EdEXCEL': ExamData(
      title: 'Edexcel (International)',
      country: 'UK',
      items: [
        'IGCSE Subjects',
        'A-Level Subjects',
        'International GCSE',
      ],
    ),

    // US Exams
    'SAT': ExamData(
      title: 'SAT',
      country: 'US',
      items: [
        'Reading & Writing',
        'Math',
      ],
      isTestSections: true,
    ),
    'PSAT': ExamData(
      title: 'PSAT',
      country: 'US',
      items: [
        'Reading & Writing',
        'Math',
      ],
      isTestSections: true,
    ),
    'ACT': ExamData(
      title: 'ACT',
      country: 'US',
      items: [
        'English',
        'Math',
        'Reading',
        'Science',
        'Writing (optional)',
      ],
      isTestSections: true,
    ),
    'AP': ExamData(
      title: 'AP',
      country: 'US',
      items: [
        'AP Calculus',
        'AP Statistics',
        'AP Biology',
        'AP Chemistry',
        'AP Physics',
        'AP Computer Science',
        'AP Economics',
        'AP Psychology',
        'AP World History',
        'AP Government',
        'AP English',
      ],
    ),

    // Australia Exams
    'ATAR': ExamData(
      title: 'ATAR',
      country: 'Australia',
      items: [
        'English',
        'Mathematics (General)',
        'Mathematics (Methods)',
        'Mathematics (Specialist)',
        'Biology',
        'Chemistry',
        'Physics',
        'Economics',
        'Business',
        'Accounting',
        'Legal Studies',
        'Psychology',
        'Computer Science/IT',
      ],
    ),
    'HSC': ExamData(
      title: 'HSC (New South Wales)',
      country: 'Australia',
      items: [
        'English (Standard/Advanced)',
        'Mathematics (Standard/Advanced/Extension)',
        'Biology',
        'Chemistry',
        'Physics',
        'Economics',
        'Business Studies',
        'Legal Studies',
        'Psychology',
        'Software Design',
      ],
    ),
    'VCE': ExamData(
      title: 'VCE (Victoria)',
      country: 'Australia',
      items: [
        'English',
        'Mathematics (General/Methods/Specialist)',
        'Biology',
        'Chemistry',
        'Physics',
        'Economics',
        'Business Management',
        'Accounting',
        'Legal Studies',
        'Psychology',
        'Computing',
      ],
    ),
    'QCE': ExamData(
      title: 'QCE (Queensland)',
      country: 'Australia',
      items: [
        'English',
        'Mathematics (General/Methods/Specialist)',
        'Biology',
        'Chemistry',
        'Physics',
        'Economics',
        'Business',
        'Accounting',
        'Legal Studies',
        'Psychology',
        'Digital Solutions',
      ],
    ),

    // Malaysia Exams
    'SPM': ExamData(
      title: 'SPM',
      country: 'Malaysia',
      items: [
        'Bahasa Melayu',
        'English',
        'Mathematics',
        'Additional Mathematics',
        'Sejarah',
        'Biology',
        'Chemistry',
        'Physics',
        'Accounting',
        'Business',
        'Economics',
        'Computer Science',
      ],
    ),
    'STPM': ExamData(
      title: 'STPM',
      country: 'Malaysia',
      items: [
        'General Studies',
        'Mathematics',
        'Further Mathematics',
        'Biology',
        'Chemistry',
        'Physics',
        'Economics',
        'Business Studies',
        'Accounting',
      ],
    ),
    'Matrikulasi': ExamData(
      title: 'Matrikulasi',
      country: 'Malaysia',
      items: [
        'Mathematics',
        'Chemistry',
        'Physics',
        'Biology',
        'Accounting',
        'Economics',
        'Business',
      ],
    ),
    'UPSR': ExamData(
      title: 'UPSR',
      country: 'Malaysia',
      items: [
        'Bahasa Melayu',
        'English',
        'Mathematics',
        'Science',
      ],
    ),
  };

  static ExamData? getExamData(String examType) {
    return _examMap[examType];
  }

  static List<String> getSubjects(String examType) {
    return _examMap[examType]?.items ?? [];
  }

  static bool isTestSections(String examType) {
    return _examMap[examType]?.isTestSections ?? false;
  }

  static List<String> getTopics(String examType, String subject) {
    return examSubjectTopics[examType]?[subject] ?? [];
  }
}